return {
  "nvim-orgmode/orgmode",
  version = "*",
  event = "BufEnter *.org",
  dependencies = { "nvim-treesitter/nvim-treesitter" },
  config = function()
    require("orgmode").setup({
      org_agenda_files = { "~/Documents/org/**/*" },
      org_default_notes_file = "~/Documents/org/refile.org",
      org_todo_keywords = { "TODO(t)", "NEXT(n)", "WAITING(w)", "DONE(d)", "CANCELLED(c)" },
      org_todo_keyword_faces = {
        TODO = ":foreground #61afef :weight bold",
        NEXT = ":foreground #e5c07b :weight bold",
        WAITING = ":foreground #d19a66 :weight bold",
        DONE = ":foreground #98c379 :weight bold",
        CANCELLED = ":foreground #5c6370 :strikethrough :weight bold",
      },
      org_highlight_latex_and_related = "native",
      org_ellipsis = " 󰁤",
      org_indent = { enable = true },
      org_hide_emphasis_markers = true,
      org_startup_folded = "inherit",
      org_startup_indented = true,
      org_agenda_start_on_weekday = 1,
      org_agenda_span = "week",
      org_agenda_start_day = "today",
      org_capture_templates = {
        t = {
          description = "Todo",
          template = "* TODO %?\n %T",
          target = "~/Documents/org/todos.org",
        },
        j = {
          description = "Journal",
          template = "\n*** %<%Y-%m-%d %H:%M>\n%?\n\n",
          target = "~/Documents/org/journal.org",
        },
        n = {
          description = "Note",
          template = "* %?\n%T",
          target = "~/Documents/org/notes.org",
        },
      },
      org_plugin_calendar = { enabled = true },
      org_plugin_capture = { enabled = true },
      org_plugin_clock = { enabled = true },
      org_plugin_conceal = { enabled = true },
      org_plugin_highlights = { enabled = true },
      org_plugin_indent = { enabled = true },
      org_plugin_links = { enabled = true },
      org_plugin_nl = { enabled = true },
      org_plugin_progress = { enabled = true },
      org_plugin_property = { enabled = true },
      org_plugin_qf = { enabled = true },
      org_plugin_search = { enabled = true },
      org_plugin_stable_sort = { enabled = true },
      org_plugin_time = { enabled = true },
      org_plugin_which_key = { enabled = true },
    })
  end,
}
